#!/bin/bash

# Save the directory of the script
SCRIPT_DIR=$(dirname "$(realpath "$0")")

# Change to the script's directory
cd "$SCRIPT_DIR"

# Run the Python script and pass standard input to it
bin/python3 src/mimas-agent.py
